/**:
  ros__parameters:
    use_intra_process_comms: true

/**/web_video_server:
  ros__parameters:
    port: 8081

/**/main_camera:
  ros__parameters:
    camera: 0
    frame_id: 'main_camera_link'
    width: 640
    height: 480
    format: 'YUYV'
    StatsOutputEnable: false
