variables:
  IMAGE_ARTIFACT_PATTERN: "build-clover2-image/clover2-*.img"

stages:
  - docker
  - image

.docker-setup: &docker-task
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - |
      if [ "$CI_COMMIT_REF_NAME" = "master" ]; then
        export BUILD_MODE=master
      elif [ -n "$CI_COMMIT_TAG" ]; then
        export BUILD_MODE=release
      elif [ -n "$CI_MERGE_REQUEST_ID" ]; then
        export BUILD_MODE=develop
      elif [ "$CI_PIPELINE_SOURCE" = "push" ]; then
        export BUILD_MODE=develop
      else
        echo "Unexpected BUILD_MODE. Check rules"
        exit -1
      fi

    - echo "BUILD_MODE=$BUILD_MODE"

    - apk add --no-cache make

    - echo "$DOCKER_REGISTRY_PASSWORD" | docker login registry.gitlab.com --username $DOCKER_REGISTRY_USER --password-stdin
  after_script:
    - echo "Fixing permissions for cleanup..."
    - sudo chown -R $(id -u):$(id -g) . 2>/dev/null || true
  cache:
    key: "global"
    paths:
      - .cache/

.docker-bake: &docker-bake
  <<: *docker-task
  script:
    - make clover2-bake-$BAKE_TARGET
    - make clover2-bake-push-$BAKE_TARGET

docker-build-px4:
  <<: *docker-bake
  stage: docker
  variables:
    BAKE_TARGET: "px4"

docker-build-ros:
  <<: *docker-bake
  stage: image
  variables:
    BAKE_TARGET: "ros"

docker-build-tooling:
  <<: *docker-bake
  stage: docker
  variables:
    BAKE_TARGET: "tooling"

docker-build-docs:
  <<: *docker-bake
  stage: docker
  variables:
    BAKE_TARGET: "clover2-docs"

docker-build-frontend:
  <<: *docker-bake
  stage: docker
  variables:
    BAKE_TARGET: "clover2-frontend"

docker-build-wetty:
  <<: *docker-bake
  stage: docker
  variables:
    BAKE_TARGET: "clover2-wetty"
