services:
  clover2-docs:
    build: docs
    ports:
      - "81:81"

  clover2-gui:
    build: frontend
    ports:
      - "80:80"

  clover2-wetty:
    image: wettyoss/wetty
    command: "--ssh-host clover2-0000.local"
    ports:
      - 3000:3000
