version: '3'

env:
  REGISTRY: "registry.gitlab.com/coex2/clover2/"
  PROJECT_DIR: "{{.TASKFILE_DIR}}"
  VERSION:
    sh: git rev-parse --short HEAD
    # sh: cat "${PROJECT_DIR}/VERSION"
  GIT_COMMIT:
    sh: git rev-parse --short HEAD

tasks:
  clover2-docker:bake:
    vars:
      GROUP: '{{.GROUP | default "all"}}'
    cmds:
      - docker buildx bake --progress=plain {{.GROUP}}

  clover2-image:download:
    cmds:
      - ${PROJECT_DIR}/tooling/builder/download.py --configuration clover2-ubuntu24 --output ${PROJECT_DIR}/build-clover2-image/clover2-${GIT_COMMIT}.img

  clover2-image:build:
    cmds:
      - ${PROJECT_DIR}/tooling/builder/builder.py --sudo --output ${PROJECT_DIR}/build-clover2-image/clover2-${GIT_COMMIT}.img

  clean:
    cmds:
      - rm -rf ${PROJECT_DIR}/build-*-image ${PROJECT_DIR}/docs/build
