name: Detect Version
description: Determine the build type and populate the variables

outputs:
  build_mode:
    description: develop or master or release build mode
    value: ${{ steps.detect.outputs.build_mode }}
  git_hash:
    description: Short git hash
    value: ${{ steps.detect.outputs.git_hash }}
  version:
    description: Version from tag
    value: ${{ steps.detect.outputs.version }}

runs:
  using: composite
  steps:
    - uses: actions/setup-python@v7
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: pip install -r ./tooling/requirements.txt

    - id: detect
      shell: bash
      run: |
        BASE_VERSION=$(python3 tooling/scripts/version_manager.py -vvv -d . print --main-only)
        HASH="${{ github.sha }}"
        GIT_HASH="${HASH:0:7}"
        echo "git_hash=${GIT_HASH}" >> "$GITHUB_OUTPUT"

        case "${{ github.ref }}" in
          refs/heads/master)
            echo "build_mode=master" >> "$GITHUB_OUTPUT"
            echo "version=${BASE_VERSION}+${GIT_HASH}" >> "$GITHUB_OUTPUT"
            ;;
          refs/tags/v*)
            echo "build_mode=release" >> "$GITHUB_OUTPUT"
            echo "version=${BASE_VERSION}" >> "$GITHUB_OUTPUT"
            ;;
          *)
            echo "build_mode=develop" >> "$GITHUB_OUTPUT"
            echo "version=${BASE_VERSION}+${GIT_HASH}" >> "$GITHUB_OUTPUT"
            ;;
        esac
