<?xml version='1.0' encoding='UTF-8'?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>clover2</name>
  <version>0.1.8</version>
  <description>TODO: Package description</description>
  <maintainer email="2663161@mail.ru">l_motya</maintainer>
  <license>TODO: License declaration</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <buildtool_depend>ament_cmake_python</buildtool_depend>

  <depend>rclpy</depend>
  <depend>geometry_msgs</depend>
  <depend>sensor_msgs</depend>
  <depend>bondpy</depend>
  <depend>cv_bridge</depend>

  <depend>clover2_aruco</depend>
  <depend>clover2_bringup</depend>
  <depend>clover2_cam_feature</depend>
  <depend>clover2_common</depend>
  <depend>clover2_description</depend>
  <depend>clover2_fcu_bridge</depend>
  <depend>clover2_led</depend>
  <depend>clover2_led_msgs</depend>
  <depend>clover2_map</depend>
  <depend>clover2_mavros</depend>
  <depend>clover2_nav_msgs</depend>
  <depend>clover2_optical_flow</depend>
  <depend>clover2_pose_msgs</depend>
  <depend>clover2_ui</depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
