/**/notification:
  ros__parameters:
    providers:
      - diagnostics

    output_plugins:
      - led_strip

    diagnostics:
      topic: /diagnostics_agg
      ignore_names:
        - "/Aggregation"
        - "/Aggregation/Other"
        - "/Aggregation/Other/*"
        - "/Aggregation/System"
        - "/Aggregation/System/*"
        - "/Aggregation/Vision"
        - "/Aggregation/Localization"
        - "/Aggregation/FCU"

    led_strip:
      plugin: led
      base_path: led_strip

      defaults:
        warn:
          priority: 1
          animation: blink
          color: [255, 255, 0]
          brightness: 0.7
          period: 1.0
          duration: 3.0

        error:
          priority: 2
          animation: blink
          color: [255, 0, 0]
          brightness: 1.0
          period: 0.3
          duration: 3.0

        stale:
          priority: 3
          animation: blink
          color: [0, 0, 255]
          brightness: 0.7
          period: 1.5
          duration: 3.0

      override_names:
        - power
        - fcu_backend

      overrides:
        power:
          diagnostic_name: "Power"
          animation: blink
          color: [255, 128, 0]
          brightness: 0.8
          period: 0.8
          duration: 3.0

        fcu_backend:
          diagnostic_name: "FCU backend"
          animation: blink
          color: [255, 0, 0]
          brightness: 1.0
          period: 0.15
          duration: 3.0