/**:
  ros__parameters:
    use_intra_process_comms: true

/**/aruco_tracker:
  ros__parameters:
    tracking: "base_link"

/**/fcu_bridge:
  ros__parameters:
    backend: "mavros"
    speed_limit: 1.0
    tolerance: 0.15
    slowdown_distance: 0.5

/**/web_video_server:
  ros__parameters:
    port: 8081
