# Default sensor params for imx219
# Please set `camera` parameter for select specific device

/**:
  ros__parameters:
    use_intra_process_comms: true
    # camera: 0
    AeEnable: false
    AnalogueGain: 8.0
    ExposureTime: 1000
    FrameDurationLimits: [33333, 33333]
    format: "RGB888"
    height: 480
    width: 640
