main_camera:
  enable: true
  feature_detector: true
front_camera:
  enable: false
optical_flow:
  enable: true
fcu_bridge:
  fcu_conn: uart
localization:
  enable: true
  map_server:
    enable: true
    map_filename: example-1.yaml
  aruco_tracker:
    enable: true
2d_lidar:
  enable: false
