events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    server {
        listen 81;
        server_name localhost;
        root /usr/share/nginx/html;

        location / {
            return 301 /ru;
        }

        location /ru {
            try_files $uri $uri/ /ru/index.html;
        }

        location /en {
            try_files $uri $uri/ /en/index.html;
        }

        gzip on;
        gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;
    }
}
