name: Cleanup Container Registry
on:
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:
  pull_request:

permissions:
  packages: write

jobs:
  clean-ghcr:
    runs-on: ubuntu-latest
    steps:
      - name: Purge old container versions
        uses: snok/container-retention-policy@v3.1.0
        with:
          account: ${{ github.actor }}
          token: ${{ github.token }}
          image-names: "clover2/*"
          cut-off: "1w"
          keep-at-least: 5
          image-tags: "!latest !stable"
          dry-run: false
          tag-selection: both
